openapi: 3.0.1
info:
  title: OnboardMe API
  description: API for the OnboardMe project
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Hello Endpoint
      responses:
        '200':
          description: Returns a hello message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, World!"
